Repository CaptionLive/CaptionLive, pull requests merged in 2023-07, with the labels that each got.

#148 chore: modify
  frontend/src/pages/MyOrganizations/AboutOrganization.js
Labels: Chore

#149 chore: cd test 1
  frontend/src/pages/MyOrganizations/AboutOrganization.js
Labels: Chore

#152 <Chore: Push to Production v0.0.2>
  api/src/main/java/com/aguri/captionlive/service/impl/RequestServiceImpl.java
Labels: Push to Prod

#135 <feat: share info>
  api/src/main/java/com/aguri/captionlive/DTO/Re4Orgs.java
  api/src/main/java/com/aguri/captionlive/DTO/Re4Users.java
  api/src/main/java/com/aguri/captionlive/controller/ProjectController.java
  api/src/main/java/com/aguri/captionlive/repository/AccessRepository.java
  api/src/main/java/com/aguri/captionlive/repository/OwnershipRepository.java
Labels: Feature

#156 feature: frontend basic share project
  frontend/src/App.css
  frontend/src/components/Layout/Sidebar/Sidebar.js
  frontend/src/components/Project/ShareProject.js
  frontend/src/components/Project/Worksheet.js
  frontend/src/redux/layoutSlice.js
  frontend/src/services/organization.js
Labels: Feature

#153 bugfix: duplicate request
  api/src/main/java/com/aguri/captionlive/repository/RequestRepository.java
  api/src/main/java/com/aguri/captionlive/service/impl/MessageServiceImpl.java
  api/src/main/java/com/aguri/captionlive/service/impl/RequestServiceImpl.java
Labels: Bugfix

#159 Bugfix: creating duplicate accesses
  api/src/main/java/com/aguri/captionlive/repository/AccessRepository.java
  api/src/main/java/com/aguri/captionlive/service/impl/ProjectServiceImpl.java
Labels: Bugfix

#154 <feat: rewrite jwt filter>
  api/src/main/java/com/aguri/captionlive/common/filter/JwtAuthenticationFilter.java
Labels: Feature

#161 The filter intercepts the swagger service
  api/src/main/java/com/aguri/captionlive/common/filter/JwtAuthenticationFilter.java
Labels: Bugfix

#162 hotfix: docker file mnt
  docker-compose/docker-compose-dev.yml
  docker-compose/docker-compose-fe-dev.yml
  docker-compose/docker-compose-prod.yml
Labels: Hotfix

#164 feat: signUp with nickname
  api/src/main/java/com/aguri/captionlive/controller/AuthController.java
Labels: Feature

#165 Chore/no ref/frontend api filter
  frontend/src/api/organization.js
  frontend/src/api/project.js
  frontend/src/api/request.js
  frontend/src/api/user.js
  frontend/src/components/InfoCard/Avatar.js
  frontend/src/components/InfoCard/UserInfo.js
  frontend/src/components/Layout/Header/Header.js
  frontend/src/components/User/SignUp.js
  frontend/src/pages/AllOrganizations/AllOrganizations.js
  frontend/src/pages/Mail/AllMails.js
  frontend/src/pages/MyOrganizations/AboutOrganization.js
  frontend/src/pages/MyOrganizations/Projects.js
  frontend/src/pages/MyProjects/AccessibleProjects.js
  frontend/src/redux/layoutSlice.js
  frontend/src/services/auth.js
Labels: Chore

#172 <Chore: Push to Production v1.0.1>
  frontend/src/App.css
  frontend/src/assets/workflows.js
  frontend/src/components/Project/Worksheet.js
Labels: Push to Prod

#185 Feature/no ref/renaming frontend title
  frontend/src/assets/sidebar.js
  frontend/src/components/InfoCard/EntityInfo.js
  frontend/src/components/Layout/Sidebar/Sidebar.js
  frontend/src/components/Layout/Sidebar/Sidebarlvl2.js
  frontend/src/pages/AllOrganizations/AllOrganizations.js
  frontend/src/pages/Mail/AllMails.js
  frontend/src/pages/Mail/SentMails.js
  frontend/src/pages/Mail/UnreadMails.js
  frontend/src/pages/MyHome/MyHome.js
  frontend/src/pages/MyProjects/AccessibleProjects.js
  frontend/src/pages/MyProjects/CommittedProjects.js
  frontend/src/services/request.js
Labels: Feature

#167 <feat: page query for organizaiton
  api/src/main/java/com/aguri/captionlive/controller/OrganizationController.java
  api/src/main/java/com/aguri/captionlive/repository/OrganizationRepository.java
  api/src/main/java/com/aguri/captionlive/service/OrganizationService.java
  api/src/main/java/com/aguri/captionlive/service/impl/OrganizationServiceImpl.java
Labels: Feature

#168 shared user was found by ownership and access
  api/src/main/java/com/aguri/captionlive/controller/ProjectController.java
  api/src/main/java/com/aguri/captionlive/service/ProjectService.java
  api/src/main/java/com/aguri/captionlive/service/impl/ProjectServiceImpl.java
  api/src/main/java/com/aguri/captionlive/service/impl/UserServiceImpl.java
Labels: Bugfix

#189 Bugfix/fixdelete
  api/src/main/java/com/aguri/captionlive/model/Project.java
  api/src/main/java/com/aguri/captionlive/model/Task.java
  api/src/main/java/com/aguri/captionlive/service/impl/FileRecordServiceImpl.java
  api/src/main/java/com/aguri/captionlive/service/impl/ProjectServiceImpl.java
  api/src/main/java/com/aguri/captionlive/service/impl/SegmentServiceImpl.java
  api/src/main/java/com/aguri/captionlive/service/impl/TaskServiceImpl.java
Labels: Bugfix

#171 feature: frontend basic delete project
  frontend/src/components/Project/Worksheet.js
  frontend/src/services/organization.js
Labels: Feature

#192 <fix: get all accessible api>
  api/src/main/java/com/aguri/captionlive/DTO/ProjectInfo.java
  api/src/main/java/com/aguri/captionlive/common/filter/JwtAuthenticationFilter.java
  api/src/main/java/com/aguri/captionlive/model/Organization.java
  api/src/main/java/com/aguri/captionlive/model/User.java
Labels: Bugfix

#195 fix sidebar toggle, add glossary delete
  frontend/src/components/Glossary/GlossariesTable.js
  frontend/src/components/Layout/Sidebar/Sidebar.css
  frontend/src/components/Layout/Sidebar/Sidebar.js
  frontend/src/services/glossary.js
Labels: Feature, Chore

#196 Feat/no ref/fronent confirm delete
  frontend/src/components/InfoCard/Confirm.js
  frontend/src/components/Project/Segment.js
  frontend/src/components/Project/Worksheet.js
Labels: Feature
